language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls


script:
  - nosetests -v tests/test_party.py
  - nosetests -v tests/test_office.py

after_success:
  - coveralls